### ISSUE TITLE
Idee für Header-Erkennung (-> Ausblick?)

### ISSUE THREAD

**Issue by holgerzer** [huichen5796/2022-studienarbeit-hui-chen#61]
- Netz trainieren (wie bei Table detection), dass Header und Content unterscheidet.
- Also jeweils Masken erstellen mit:
        1. Header weiss, Rest schwarz -> Netz erstellen
        2. Content weiss, Rest schwarz -> Netz erstellen
- danach ist der Prozess folgendermaßen:
       1. Table detection
       2. Header detection
       3. Tablenet extrahiert nur Zellen von Header
       4. Content detection
       5. Tablenet extrahiert nur Zellen von Content -> Feststellung der Spaltenanzahl
       6. Zellen von Header ggf. verschmelzen (Ziel: Anzahl der Content-Spalten)
       7. Header und Content kombinieren in json-Objekten

**Comment by holgerzer** [comment]
Ist erstmal nur ne Idee. Wir können darüber diskutieren wenn ich wieder aus dem Urlaub zurück bin. :)

**Comment by huichen5796** [comment]
super Idee, ich werde versuchen einen geeigneten Datensatz zu finden. Es wäre großartig, wenn es einen Header und Content angemerkten Datensatz gäbe, wenn nicht, muss ich mindestens 1000 Tabellen manuell mit Masken versehen, was sehr zeitaufwändig ist. Wenn es also keinen Datensatz gibt, derzeit kann diese Idee nur als Ausblick sein.

Übrigens: Heute werde ich versuchen, gemäß _issue instraction to funciton Umform()_ einen Tabellenverarbeitungsalgorithmus zu schreiben, der nur auf Standortinformationen der Zellen basiert, und ihn mit successControl testen. Das Ergebnis werde ich dir morgen mitteilen.
